include:
  - project: 'auxdromos/auxdromos-distro'
    file: 'aws/sit/gitlab-ci/.gitlab-ci-template.yml'

deploy_sit:
  rules:
    - when: never  # Questo disabilita il job per questo modulo specifico
