include:
  - project: 'auxdromos/auxdromos-distro'
    file: 'aws/sit/gitlab-ci/.gitlab-ci-template.yml'

deploy_sit:
  stage: deploy_sit
  image:
    name: amazon/aws-cli:latest
    entrypoint: [""]
  dependencies:
    - extract_module_info
  script:
    - echo "Caricamento dell'ultima versione su istanza SIT..."
    - if [ -f module_info.env ]; then . module_info.env; fi
    - |
      # Scarica il pacchetto dal bucket S3
      aws s3 cp "s3://${S3_BUCKET_NAME}/${MODULE_NAME}/${VERSION}/" /tmp/${MODULE_NAME}/ --recursive
      
      # Recupera l'ID dell'istanza da SSM Parameter Store
      INSTANCE_ID=$(aws ssm get-parameter --name "/auxdromos/environment/sit/instance-id/${MODULE_NAME}" --query "Parameter.Value" --output text --with-decryption)
      
      if [ -z "$INSTANCE_ID" ] || [ "$INSTANCE_ID" = "None" ]; then
        echo "Errore: Impossibile trovare l'ID dell'istanza per ${MODULE_NAME} in SSM Parameter Store"
        echo "Assicurati che il parametro /auxdromos/environment/sit/instance-id/${MODULE_NAME} esista"
        exit 1
      fi
      
      # Crea un file marker con la versione attuale
      echo "${MODULE_NAME}-${VERSION}" > /tmp/current-version.txt
      
      # Carica i file sull'istanza usando SSM
      aws ssm send-command \
        --instance-ids $INSTANCE_ID \
        --document-name "AWS-RunShellScript" \
        --parameters commands=["mkdir -p /app/${MODULE_NAME}/artifacts"] \
        --region $AWS_DEFAULT_REGION
      
      # Carica i file su S3
      aws s3 cp /tmp/${MODULE_NAME}/ "s3://${S3_BUCKET_NAME}/artifacts/${MODULE_NAME}/${VERSION}/" --recursive
      aws s3 cp /tmp/current-version.txt "s3://${S3_BUCKET_NAME}/artifacts/${MODULE_NAME}/current-version.txt"
      
      # Sincronizza dall'S3 all'istanza
      aws ssm send-command \
        --instance-ids $INSTANCE_ID \
        --document-name "AWS-RunShellScript" \
        --parameters commands=["aws s3 sync s3://${S3_BUCKET_NAME}/artifacts/${MODULE_NAME}/${VERSION}/ /app/${MODULE_NAME}/artifacts/"] \
        --region $AWS_DEFAULT_REGION
      
      echo "Artefatto caricato con successo sull'istanza SIT: ${MODULE_NAME}-${VERSION}"
  only:
    - main

