FROM postgres:17.2

RUN apt-get update && apt-get install -y awscli

ENV AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
ENV AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
ENV AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}

ENTRYPOINT ["sh", "-c", "aws s3 cp s3://auxdromos-artifacts-unique/db/init_db.sql /docker-entrypoint-initdb.d/init_db.sql && docker-entrypoint.sh postgres"]