# Questo crea tutto l'ambiente di sviluppo in locale recupera i jar da s3
# creando anche i DB e Keycloak

services:
  gateway:
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/auxdromos-gateway:latest
    container_name: auxdromos-gateway
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: "dev"
      S3_BUCKET_NAME: ${S3_BUCKET_NAME}
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
    networks:
      - auxdromos-network
    depends_on:
      - backend
      - keycloak-app

  keycloak:
    image: quay.io/keycloak/keycloak:26.0.7
    container_name: auxdromos-keycloak
    ports:
      - "8082:8080"
    environment:
      DB_VENDOR: postgres
      DB_ADDR: keycloak-db
      DB_DATABASE: ${POSTGRES_DB}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
    command: start-dev
    depends_on:
      - keycloak-db
    restart: on-failure
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - auxdromos-network

  keycloak-db:
    image: postgres:14
    container_name: keycloak-db-auxdromos
    environment:
      PORT: 5433
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - keycloak-data:/var/lib/postgresql/data
    networks:
      - auxdromos-network

  keycloak-app:
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/auxdromos-idp:latest
    container_name: auxdromos-idp
    environment:
      SPRING_PROFILES_ACTIVE: "dev"
      S3_BUCKET_NAME: ${S3_BUCKET_NAME}
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
    networks:
      - auxdromos-network
    depends_on:
      - keycloak-db

  backend:
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/auxdromos-backend:latest
    container_name: auxdromos-backend
    environment:
      SPRING_PROFILES_ACTIVE: "dev"
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/auxdromos?currentSchema=auxdromos&options=-c%20search_path%3Dauxdromos
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: BbzcaI5HKm5wr3
      S3_BUCKET_NAME: ${S3_BUCKET_NAME}
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
    networks:
      - auxdromos-network
    depends_on:
      - postgres

  postgres:
    image: postgres:17.2
    container_name: postgres-db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: BbzcaI5HKm5wr3
      POSTGRES_DB: auxdromos
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - auxdromos-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d auxdromos"]
      interval: 10s
      timeout: 5s
      retries: 5

  config-server:
    build:
      context: ../
      dockerfile: Dockerfile
    container_name: auxdromos-config-server
    environment:
      SPRING_PROFILES_ACTIVE: "dev"
      S3_BUCKET_NAME: ${S3_BUCKET_NAME}
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
    command: >
      sh -c "aws s3 cp s3://auxdromos-artifacts-unique/config-server/config-server-AWS.jar /app/config-server-aws.jar &&
             java -jar /app/config-server-aws.jar"
    depends_on:
      - gateway
      - backend
      - keycloak
    networks:
      - auxdromos-network

networks:
  auxdromos-network:
    driver: bridge

volumes:
  postgres-data:
  keycloak-data: