services:
  config:
    image: hyness/spring-cloud-config-server
    container_name: auxdromos-config
    env_file:
      - ../env/config.env
    ports:
      - 8888:8888
    environment:
      - SPRING_CLOUD_CONFIG_SERVER_GIT_URI=https://gitlab.com/auxdromos/auxdromos-configuration.git
      - SPRING_CLOUD_BUS_ENABLED=false
      - SPRING_CLOUD_CONFIG_SERVER_GIT_USERNAME=oauth2
      - SPRING_CLOUD_CONFIG_SERVER_GIT_PASSWORD=glpat-icte6rcutahRVZ_72Xv5
      - SPRING_CLOUD_CONFIG_SERVER_GIT_DEFAULT_LABEL=master
      - SPRING_CLOUD_CONFIG_SERVER_GIT_SEARCH_PATHS=configs/{application},configs/{application}/{profile}
      - MANAGEMENT_ENDPOINT_HEALTH_ENABLED=true
      - MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE=health
      - JAVA_TOOL_OPTIONS=-XX:ReservedCodeCacheSize=32M -Xss256K -XX:MaxMetaspaceSize=64M -Xmx96M -XX:MaxDirectMemorySize=5M
      - BPL_JVM_THREAD_COUNT=50
      - BPL_JVM_HEAD_ROOM=0
    networks:
      - auxdromos-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  rdbms:
    image: 463470955561.dkr.ecr.us-east-1.amazonaws.com/auxdromos-rdbms:latest
    container_name: auxdromos-rdbms
    ports:
      - "${EXTERNAL_PORT}:${INTERNAL_PORT}"
    environment:
      SPRING_CLOUD_CONFIG_URI: "http://auxdromos-config:8888"
      PROFILE: "sit"
      SPRING_PROFILES_ACTIVE: "sit"
      SPRING_APPLICATION_NAME: "rdbms"
    networks:
      - auxdromos-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  keycloak:
    image: quay.io/keycloak/keycloak:26.0.7
    container_name: auxdromos-keycloak
    env_file:
      - ../env/keycloak.env
    ports:
      - "${EXTERNAL_PORT:-8082}:8080"
    environment:
      # ---- Variabili Build-Time (necessarie anche al runtime per controllo) ----
      KC_DB: postgres
      # ---- Variabili Runtime ----
      KC_DB_URL_HOST: sit-auxdromos.cjgmm0kewpv2.us-east-1.rds.amazonaws.com
      KC_DB_URL_DATABASE: sit-auxdromos
      KC_DB_USERNAME: auxdromos
      KC_DB_PASSWORD: DujDKqZHf60iiXPCtmHk # Considera l'uso di secrets o .env file per le password
      KC_DB_SCHEMA: keycloak
      KEYCLOAK_ADMIN: admin # Considera l'uso di secrets o .env file
      KEYCLOAK_ADMIN_PASSWORD: adminpassword # Considera l'uso di secrets o .env file
      KC_HOSTNAME: sit.idp.auxdromos.it
      KC_HTTP_ENABLED: 'true' # Se ALB parla HTTP con Keycloak
      KC_PROXY: edge # Fondamentale per l'operatività dietro ALB
      KC_HTTP_RELATIVE_PATH: /
      KC_HOSTNAME_STRICT: 'false' # Utile per flessibilità iniziale
      KC_HEALTH_ENABLED: 'true'
      KC_HTTP_MAX_CONNECTIONS: 50000 # Valuta se questo valore è appropriato
      QUARKUS_HTTP_ACCESS_LOG_ENABLED: 'true'
    deploy:
      resources:
        limits:
          memory: 1536M
    command: start-dev
    restart: on-failure
    networks:
      - auxdromos-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  idp:
      image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/auxdromos-idp:latest
      container_name: auxdromos-idp
      env_file:
        - ../env/idp.env
      ports:
        - "${EXTERNAL_PORT}:${INTERNAL_PORT}"
      environment:
        - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      networks:
        - auxdromos-network
      restart: unless-stopped
      logging:
        driver: "json-file"
        options:
          max-size: "10m"
          max-file: "3"

  backend:
      image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/auxdromos-backend:latest
      container_name: auxdromos-backend
      env_file:
        - ../env/backend.env
      ports:
        - "${EXTERNAL_PORT}:${INTERNAL_PORT}"
      environment:
        - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      networks:
        - auxdromos-network
      restart: unless-stopped
      logging:
        driver: "json-file"
        options:
          max-size: "10m"
          max-file: "3"

    gateway:
      image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/auxdromos-gateway:latest
      container_name: auxdromos-gateway
      env_file:
        - ../env/gateway.env
      ports:
        - "${EXTERNAL_PORT}:${INTERNAL_PORT}"
      environment:
        - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      networks:
        - auxdromos-network
      restart: unless-stopped
      logging:
        driver: "json-file"
        options:
          max-size: "10m"
          max-file: "3"

networks:
  auxdromos-network:
    driver: bridge
