version: '3.8'

# Docker Compose file for AuxDromos SIT environment
# Uses environment variables from AWS Systems Manager Parameter Store

services:
  config:
    image: hyness/spring-cloud-config-server
    container_name: auxdromos-config
    ports:
      # Uses environment variables exported by the script, with defaults for safety
      - "${EXTERNAL_PORT:-8888}:${INTERNAL_PORT:-8888}"
    environment:
      # Git configuration
      - SPRING_CLOUD_CONFIG_SERVER_GIT_URI=${SPRING_CLOUD_CONFIG_SERVER_GIT_URI}
      - SPRING_CLOUD_CONFIG_SERVER_GIT_USERNAME=${SPRING_CLOUD_CONFIG_SERVER_GIT_USERNAME}
      - SPRING_CLOUD_CONFIG_SERVER_GIT_PASSWORD=${SPRING_CLOUD_CONFIG_SERVER_GIT_PASSWORD}
      - SPRING_CLOUD_CONFIG_SERVER_GIT_DEFAULT_LABEL=${SPRING_CLOUD_CONFIG_SERVER_GIT_DEFAULT_LABEL}
      - SPRING_CLOUD_CONFIG_SERVER_GIT_SEARCH_PATHS=${SPRING_CLOUD_CONFIG_SERVER_GIT_SEARCH_PATHS}
      # Fixed values
      - SPRING_CLOUD_BUS_ENABLED=false
      - MANAGEMENT_ENDPOINT_HEALTH_ENABLED=true
      - MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE=health
      # Java options - increased memory limits
      - JAVA_TOOL_OPTIONS=-XX:ReservedCodeCacheSize=64M -Xss512K -XX:MaxMetaspaceSize=128M -Xmx256m -XX:MaxDirectMemorySize=32M -XX:MaxRAMPercentage=75.0
      - BPL_JVM_THREAD_COUNT=50
      - BPL_JVM_HEAD_ROOM=0
      # Spring profile
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE:-sit}
    networks:
      - auxdromos-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  rdbms:
    # Usa variabili d'ambiente per tag, account e regione
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/auxdromos-rdbms:${RDBMS_IMAGE_TAG:-latest}
    container_name: auxdromos-rdbms
    ports:
      # Usa le variabili d'ambiente esportate dallo script
      - "${EXTERNAL_PORT:-8089}:${INTERNAL_PORT:-8089}" # Aggiunti default
    environment:
      # Queste verranno lette dall'ambiente esterno (esportate dallo script)
      SPRING_CLOUD_CONFIG_URI: "http://auxdromos-config:8888" # Fisso
      PROFILE: "${PROFILE:-sit}"
      SPRING_PROFILES_ACTIVE: "${SPRING_PROFILES_ACTIVE:-sit}"
      SPRING_APPLICATION_NAME: "rdbms" # Fisso
      JAVA_TOOL_OPTIONS: "-Xmx576m -XX:MaxRAMPercentage=75.0" # Fisso
    deploy:
      resources:
        limits:
          memory: 768M
    restart: no
    networks:
      - auxdromos-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  keycloak:
    # Immagine Keycloak standard
    image: quay.io/keycloak/keycloak:26.0.7
    container_name: auxdromos-keycloak
    ports:
      # Usa le variabili d'ambiente esportate dallo script
      - "${EXTERNAL_PORT:-8082}:${INTERNAL_PORT:-8080}" # Aggiunti default
      - "9090:9000"
    environment:
      # Queste verranno lette dall'ambiente esterno (esportate dallo script)
      KC_DB: ${KC_DB:-postgres}
      KC_DB_URL_HOST: ${KC_DB_URL_HOST}
      KC_DB_URL_DATABASE: ${KC_DB_URL_DATABASE}
      KC_DB_USERNAME: ${KC_DB_USERNAME}
      KC_DB_PASSWORD: ${KC_DB_PASSWORD} # Letta da env (SecureString da SSM)
      KC_DB_SCHEMA: ${KC_DB_SCHEMA:-keycloak}
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD} # Letta da env (SecureString da SSM)
      KC_HOSTNAME: ${KC_HOSTNAME:-sit.idp.auxdromos.it}
      KC_HTTP_ENABLED: ${KC_HTTP_ENABLED:-true}
      KC_PROXY: ${KC_PROXY:-edge}
      KC_HTTP_RELATIVE_PATH: ${KC_HTTP_RELATIVE_PATH:-/}
      KC_HOSTNAME_ADMIN: ${KC_HOSTNAME_ADMIN:-sit.idp.auxdromos.it}
      KC_HOSTNAME_STRICT_HTTPS: ${KC_HOSTNAME_STRICT_HTTPS:-true}
      KC_HOSTNAME_STRICT: ${KC_HOSTNAME_STRICT:-false}
      KC_HEALTH_ENABLED: ${KC_HEALTH_ENABLED:-true}
      KC_HTTP_MAX_CONNECTIONS: ${KC_HTTP_MAX_CONNECTIONS:-50000}
      QUARKUS_HTTP_ACCESS_LOG_ENABLED: ${QUARKUS_HTTP_ACCESS_LOG_ENABLED:-true}
    deploy:
      resources:
        limits:
          memory: 1536M
        reservations:
          memory: 1G
    command: start
    restart: unless-stopped
    networks:
      - auxdromos-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  idp:
    # Usa variabili d'ambiente per tag, account e regione
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/auxdromos-idp:${IDP_IMAGE_TAG:-latest}
    container_name: auxdromos-idp
    ports:
      # Usa le variabili d'ambiente esportate dallo script
      - "${EXTERNAL_PORT:-8081}:${INTERNAL_PORT:-8081}" # Aggiunti default
    environment:
      # Queste verranno lette dall'ambiente esterno (esportate dallo script)
      SPRING_CLOUD_CONFIG_URI: "http://auxdromos-config:8888" # Fisso
      PROFILE: "${PROFILE:-sit}"
      SPRING_PROFILES_ACTIVE: "${SPRING_PROFILES_ACTIVE:-sit}"
      SPRING_APPLICATION_NAME: "idp" # Fisso
      JAVA_TOOL_OPTIONS: "-Xmx576m -XX:MaxRAMPercentage=75.0" # Fisso
    deploy:
      resources:
        limits:
          memory: 768M
    networks:
      - auxdromos-network
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  backend:
    # Uses environment variables for tag, account, and region
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/auxdromos-backend:${BACKEND_IMAGE_TAG:-latest}
    container_name: auxdromos-backend
    ports:
      # Uses environment variables exported by the script
      - "${EXTERNAL_PORT:-8083}:${INTERNAL_PORT:-8083}" # Added defaults
    environment:
      # These are read from external environment (exported by the script)
      SPRING_CLOUD_CONFIG_URI: "http://auxdromos-config:8888" # Fixed
      PROFILE: "${PROFILE:-sit}"
      SPRING_PROFILES_ACTIVE: "${SPRING_PROFILES_ACTIVE:-sit}"
      SPRING_APPLICATION_NAME: "backend" # Fixed
      JAVA_TOOL_OPTIONS: "-Xmx768m -XX:MaxRAMPercentage=75.0" # Fixed
    deploy:
      resources:
        limits:
          memory: 1G
    networks:
      - auxdromos-network
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  gateway:
    # Uses environment variables for tag, account, and region
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/auxdromos-gateway:${GATEWAY_IMAGE_TAG:-latest}
    container_name: auxdromos-gateway
    ports:
      # Uses environment variables exported by the script
      - "${EXTERNAL_PORT:-8080}:${INTERNAL_PORT:-8080}" # Added defaults
    environment:
      # These are read from external environment (exported by the script)
      SPRING_CLOUD_CONFIG_URI: "http://auxdromos-config:8888" # Fixed
      PROFILE: "${PROFILE:-sit}"
      SPRING_PROFILES_ACTIVE: "${SPRING_PROFILES_ACTIVE:-sit}"
      SPRING_APPLICATION_NAME: "gateway" # Fixed
      JAVA_TOOL_OPTIONS: "-Xmx576m -XX:MaxRAMPercentage=75.0" # Fixed
    deploy:
      resources:
        limits:
          memory: 768M
    networks:
      - auxdromos-network
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  print-service:
    # Uses environment variables for tag, account, and region
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/auxdromos-print-service:${PRINT_SERVICE_IMAGE_TAG:-latest}
    container_name: auxdromos-print-service
    ports:
      # Uses environment variables exported by the script
      - "${EXTERNAL_PORT:-8085}:${INTERNAL_PORT:-8085}" # Added defaults
    environment:
      # These are read from external environment (exported by the script)
      SPRING_CLOUD_CONFIG_URI: "http://auxdromos-config:8888" # Fixed
      PROFILE: "${PROFILE:-sit}"
      SPRING_PROFILES_ACTIVE: "${SPRING_PROFILES_ACTIVE:-sit}"
      SPRING_APPLICATION_NAME: "print-service" # Fixed
      JAVA_TOOL_OPTIONS: "-Xmx768m -XX:MaxRAMPercentage=75.0" # Fixed
    deploy:
      resources:
        limits:
          memory: 1G
    networks:
      - auxdromos-network
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  admin-dashboard:
    # Uses environment variables for tag, account, and region
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/auxdromos-admin-dashboard:${PRINT_SERVICE_IMAGE_TAG:-latest}
    container_name: auxdromos-admin-dashboard
    ports:
      # Uses environment variables exported by the script
      - "${EXTERNAL_PORT:-8086}:${INTERNAL_PORT:-8086}" # Added defaults
    environment:
      # These are read from external environment (exported by the script)
      SPRING_CLOUD_CONFIG_URI: "http://auxdromos-config:8888" # Fixed
      PROFILE: "${PROFILE:-sit}"
      SPRING_PROFILES_ACTIVE: "${SPRING_PROFILES_ACTIVE:-sit}"
      SPRING_APPLICATION_NAME: "admin-dashboard" # Fixed
      JAVA_TOOL_OPTIONS: "-Xmx768m -XX:MaxRAMPercentage=75.0" # Fixed
    deploy:
      resources:
        limits:
          memory: 1G
    networks:
      - auxdromos-network
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  auxdromos-network:
    external: true
