# .github/workflows/main.yml
name: DISTRO CI/CD

on:
  push:
    branches:
      - main
      - develop
      - 'feature/**'
  pull_request:
    branches:
      - main
      - develop

jobs:
  call-reusable-pipeline:
    name: Run Shared AuxDromos CI/CD
    uses: ./.github/workflows/reusable-ci-template.yml

    permissions:
      id-token: write
      contents: read

    with:
      java-version: '17'

    # Rimuovi tutti i segreti AWS/EC2. Non serve più passarli.
    secrets: {}
    # Oppure, se hai definito i segreti a livello di repository/organizzazione
    # e vuoi passare solo quelli che potrebbero servire in futuro (ma non ora):
    # secrets: inherit
