# .github/workflows/main.yml
name: DISTRO CI/CD

on:
  push:
    branches:
      - main
      - develop
      - 'feature/**'
  pull_request:
    branches:
      - main
      - develop

jobs:
  call-reusable-pipeline:
    name: Run Shared AuxDromos CI/CD
    uses: ./.github/workflows/reusable-ci-template.yml

    permissions:
      id-token: write
      contents: read
      actions: write

    with:
      java-version: '17'
      artifact-retention-days: 7  # Imposta la soglia di età a 14 giorni
    secrets:
      GITHUB_PACKAGES_TOKEN: ${{ secrets.GH_PACKAGES_TOKEN }}
