# .github/workflows/main.yml
name: DISTRO CI/CD

on:
  push:
    branches:
      - main
      - develop
      - 'feature/**'
  pull_request:
    branches:
      - main
      - develop

jobs:
  call-reusable-pipeline:
    name: Run Shared AuxDromos CI/CD
    uses: ./.github/workflows/reusable-ci-template.yml

    permissions:
      id-token: write
      contents: read

    with:
      java-version: '17'
      github-packages: true
    secrets:
      GITHUB_TOKEN: ${{ secrets.GH_PACKAGES_TOKEN }}
