# .github/workflows/main.yml
# Workflow per il modulo DISTRO che chiama la pipeline riutilizzabile
name: DISTRO CI/CD

on:
  push:
    branches:
      - main
      - develop
      - 'feature/**'
  pull_request:
    branches:
      - main
      - develop

jobs:
  call-reusable-pipeline:
    name: Run Shared AuxDromos CI/CD
    # Specifica il percorso del workflow riutilizzabile nello stesso repository 'distro'
    # Quando si usa un path locale, NON si specifica la versione (@main, @tag, @sha)
    # GitHub usa automaticamente la versione dello stesso commit.
    uses: ./.github/workflows/reusable-ci-template.yml # Rimuovi @main
    # Passa gli input richiesti (se ce ne sono oltre ai default)
    with:
      java-version: '17' # Puoi omettere se '17' è il default desiderato

    # Passa i segreti richiesti dal workflow riutilizzabile.
    # Questi segreti devono essere definiti nelle impostazioni di QUESTO repository (auxdromos-distro).
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      EC2_USER: ${{ secrets.EC2_USER }}
      EC2_HOST: ${{ secrets.EC2_HOST }}
      EC2_PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}
      # BUILD_ARGS: ${{ secrets.BUILD_ARGS }} # Passa questo se il template lo richiede e lo usi

    # Alternativa più concisa se i nomi dei segreti corrispondono:
    # secrets: inherit
